spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yeyeling/springcloudconfig.git # 配置服务中心的仓库网址
          search-paths: springcloudconfig # 配置仓库路径
          default-label:  master # 配置仓库的分支。如果是本地读取，可不配置
          username: 1146517161@qq.com
          password: psw18792276566
test